USE [master]
GO

/****** Object:  Database [TesteProgramador]    Script Date: 12/06/2021 14:29:49 ******/
CREATE DATABASE [TesteProgramador]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TesteProgramador', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TesteProgramador.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TesteProgramador_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TesteProgramador_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TesteProgramador].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TesteProgramador] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TesteProgramador] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TesteProgramador] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TesteProgramador] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TesteProgramador] SET ARITHABORT OFF 
GO

ALTER DATABASE [TesteProgramador] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TesteProgramador] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TesteProgramador] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TesteProgramador] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TesteProgramador] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TesteProgramador] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TesteProgramador] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TesteProgramador] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TesteProgramador] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TesteProgramador] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TesteProgramador] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TesteProgramador] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TesteProgramador] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TesteProgramador] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TesteProgramador] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TesteProgramador] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TesteProgramador] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TesteProgramador] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TesteProgramador] SET  MULTI_USER 
GO

ALTER DATABASE [TesteProgramador] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TesteProgramador] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TesteProgramador] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TesteProgramador] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TesteProgramador] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TesteProgramador] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TesteProgramador] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TesteProgramador] SET  READ_WRITE 
GO

